export const TYPES = {
    GET_COUNTRIES: "GET_COUNTRIES",
    GET_DETAILS: "GET_DETAILS",
    GET_COUNTRIES_NAME: "GET_COUNTRIES_NAME",
    FILTER_BY_CONTINENT: "FILTER_BY_CONTINENT",
    ADD_ACTIVITIES: "ADD_ACTIVITIES",
    GET_ACTIVITIES: "GET_ACTIVITIES",
    FILTER_BY_ACTIVITIES: "FILTER_BY_ACTIVITIES",
    FILTER_POPULATION_HIGHER: "ORDER_POPULATION_HIGHER",
    FILTER_POPULATION_SMALLER: "ORDER_POPULATION_SMALLER",
    ORDER_ALPHABETICAL_AZ: "ORDER_ALPHABETICAL_AZ",
    ORDER_ALPHABETICAL_ZA: "ORDER_ALPHABETICAL_ZA",
};